runtime: go
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "1.20"
env: flex
instance_class: F1
includes:
  - ./production.secret.yaml
service_account: be-yamaguchi-kohei@appspot.gserviceaccount.com
beta_settings:
  cloud_sql_instances: be-yamaguchi-kohei:us-central1:google-cloud-go=tcp:3306
